spring:
  application:
    name: secureconnect
  datasource:
    url: jdbc:postgresql://localhost:5432/secureconnect
    username: postgres
    password: Dimple22
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: PASTE_YOUR_GENERATED_KEY_HERE
  expiration: 86400000